### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [dlr-eoc/ukis-pysat#30]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary ukis-pysat -w /tmp/ext ukis-pysat==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting ukis-pysat==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/bb0/9df8106b1d6c7/ukis-pysat-0.2.0.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-qv8a31e2/ukis-pysat/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-qv8a31e2/ukis-pysat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-qv8a31e2/ukis-pysat/pip-egg-info
         cwd: /tmp/pip-wheel-qv8a31e2/ukis-pysat/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-qv8a31e2/ukis-pysat/setup.py", line 37, in <module>
        install_requires=open("requirements.txt").read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
This appears to work with pip 20 and fail with pip 19

**Comment by fwfichtner** [comment]
Thanks for the contribution. How do we fix this, by including a `MANIFEST.in` file to include the missing files?

**Comment by thatch** [comment]
You got it, `MANIFEST.in` that lists the files you want included.

**Comment by fwfichtner** [comment]
Thanks, then I guess I can close. Feel free to reopen if there's still something missing.
